### ISSUE TITLE
DNAvcf and RNABam

### ISSUE THREAD

**Issue by everestial** [AJHodgkinson/ASE#1]
Should, DNAvcf and RNABam be from the same individual? What if there is no vcf from DNA?

**Comment by AJHodgkinson** [comment]
Yes, they should be from the same individual.  You will need to have SNPs called from this individual in DNA (whole genome or exome sequencing) in order for variation to be identified and flipped in the RNA reads.  You could call SNPs from RNA data, but of course there will be missing information at sites that show high biases or are genuinely under ASE, and so the approach will probably not correct the data as intended (although I have never tested this).

**Comment by everestial** [comment]
Thanks. I don't have DNAvcf from same individuals, but from other individuals from same population. So, I think I will have to work out this my way.

Thank you again.
